---
galaxy_info:
  author: Your Name
  description: Ansible role to deploy cAdvisor using Docker
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - monitoring
    - cadvisor
