---
- name: Download the redis_exporter archive
  get_url:
    url: "{{ redis_exporter_archive_url }}"
    dest: "/tmp/redis_exporter.tar.gz"

- name: Extract redis_exporter
  unarchive:
    src: "/tmp/redis_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move redis_exporter binary
  copy:
    src: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64/redis_exporter"
    dest: "/usr/local/bin/redis_exporter"
    remote_src: yes
    mode: '0755'

- name: Create redis_exporter service
  template:
    src: "redis_exporter.service.j2"
    dest: "/etc/systemd/system/redis_exporter.service"
    mode: '0644'
  tags:
    - create_redis_exporter_service

- name: Reload systemd to pick up the redis_exporter service
  systemd:
    daemon_reload: yes
  tags:
    - reload_systemd

- name: Enable and start the redis_exporter service
  systemd:
    name: redis_exporter
    state: started
    enabled: yes
  tags:
    - start_redis_exporter

