---
- name: Create node_exporter service file
  template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
    mode: '0644'
  tags:
    - create_service

- name: Reload systemd to pick up the node_exporter service
  systemd:
    daemon_reload: yes
  tags:
    - reload_systemd

- name: Enable and start the node_exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
  tags:
    - start_node_exporter
