---
- name: Download Nginx Prometheus Exporter
  get_url:
    url: "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/nginx-prometheus-exporter_{{ nginx_exporter_version }}_linux_amd64.tar.gz"
    dest: "/tmp/nginx_prometheus_exporter.tar.gz"

- name: Extract Nginx Prometheus Exporter
  unarchive:
    src: "/tmp/nginx_prometheus_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move Nginx Prometheus Exporter binary
  copy:
    src: "/tmp/nginx-prometheus-exporter"
    dest: "/usr/local/bin/nginx-prometheus-exporter"
    remote_src: yes
    mode: '0755'
