---
- name: Install prometheus & grafana using Docker
  hosts: grafana
  vars:
    prometheus_version: "latest"
    grafana_version: "latest"
    cadvisor_version: "0.46.0"
  roles:
    # - role: roles/docker
    - role: roles/prometheus-grafana
