---
# ensure we have variables from .env files
- include_tasks: ../roles/env/tasks/main.yml

- include_tasks: prometheus.yml
- include_tasks: grafana.yml

# disables loki and promtail
# - include_tasks: loki.yml
# - include_tasks: promtail.yml

