---
- name: Create a Docker network for Kibana
  docker_network:
    name: elk_network
    state: present

- name: Create kibana directory on host
  file:
    path: /etc/kibana
    state: directory
    mode: "0755"

- name: Pull Kibana Docker image
  docker_image:
    name: docker.elastic.co/kibana/kibana:{{ elk_version }}
    source: pull

# TODO rember to move CA cert from elastic to Kibana
# docker cp elasticsearch:/usr/share/elasticsearch/config/certs/http_ca.crt .
# docker cp http_ca.crt kibana:/usr/share/kibana/config/certs/ca/http_ca.crt
- name: Start Kibana container
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:{{ elk_version }}
    state: started
    restart: yes
    restart_policy: unless-stopped
    published_ports:
      - "5601:5601"
    env:
      ELASTICSEARCH_HOSTS: "{{ env_vars.ELASTIC_HOSTS }}" 
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: "{{ env_vars.KIBANA_PASSWORD }}"
      TELEMETRY_ENABLED: "false"
    networks:
      - name: elk_network

