---
- name: Include distro check tasks
  include_tasks: check_distro.yml
  tags:
    - check_distro

- name: Include Docker installation tasks if distro is supported
  include_tasks: install.yml
  when: distro_supported
  tags:
    - install
