---
- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  when: distro_supported

