---
galaxy_info:
  author: Your Name
  description: Ansible role to install and manage Docker on Debian
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - docker
dependencies: []
